### PR TITLE
fix python-past dependency

### LINKED ISSUE #18: python-past dependency not found in any repo or in AUR
This builds for now but the python package won't install because of a missing ```python-past``` dependency.

Installs when I remove that dependency but not sure if it breaks some functionality.
Can't test much as miopen-hip is currently at 3.8 and it's falling back to CPU as it doesn't find ```libamdhip64.so.3```.

### PR DESCRIPTION
**Pull request by nquest**
According to [https://pypi.org/project/past/](url) past now is part of future. Updated PKGBUILD.

Closes #18

### CODE REVIEW

**Review by acxz — APPROVED** [review]
Thanks for fixing this @nquest !

Do you mind submitting a patch to @svenstaro for the cuda based tensorflow package?
I like to keep this PKGBUILD as close as possible to the tensorflow pkgbuild already in community so that the inclusion of the rocm exclusive stuff in this PKGBUILD can be easily done when the time comes.

As I believe this change is prob needed for the community tensorflow package do you mind sending a patch over to the "upstream" tensorflow pkgbuild?

Thanks!

**Comment by nquest** [comment]
I'am really noob to sending something upstream. I'll try )

**Comment by acxz** [comment]
always a learning experience, Sven might have a repo that holds his PKGBUILDs that he maintains that you can make a PR too. Or you can email him the patch file as well. Filing a bug on the Arch bug tracker is a way to go as well if you can't connect him directly. You could also try to hit him up on IRC.

**Comment by nquest** [comment]
upstream PKGBUILD depends on python-pasta. Trying to build with it.

**Pull request merged**
